---
name: Sonarr
version: dev
slug: sonarr
description: Sonarr is a PVR for usenet and bittorrent users.
url: https://github.com/lbouriez/hassio-addons
image: ghcr.io/evilmarty/hassio-sonarr
arch:
  - aarch64
  - amd64
  - armv7
init: false
webui: "http://[HOST]:[PORT:8989]"
panel_icon: "mdi:selection-ellipse"
ports:
  8989/tcp: 8989
ports_description:
  8989/tcp: The port for the Sonarr webinterface
hassio_api: true
map:
  - media:rw
  - share:rw
  - ssl:ro
environment:
  PUID: 0
  PGID: 0
options:
  networkdisks:
    "<//SERVER/SHARE>"
  cifsusername: "<username>"
  cifspassword: "<password>"
  cifsversion: 3.0
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  networkdisks:
    str
  cifsusername: str
  cifspassword: str
  cifsversion: list(3.0|2.1|2.0|1.0)?
